service: backend

projectDir: ./

frameworkVersion: '2'
variableResolutionMode: 20210326
useDotenv: true

provider:
    name: aws
    runtime: nodejs14.x
    stage: ${opt:stage, 'dev'}
    lambdaHashingVersion: 20201221

functions:
    app:
        handler: output/server.handler
        events: 
            -   http: ANY /1972/09/11
            -   http: 'ANY (proxy+)'


plugins:
  - serverless-offline
