service: backend
package:
  patterns:
    - '!./output/**'
    - '!./src/**'
    - '!./tsconfig.json'
    - '../backend/output/server.js'
    - '../backend/output/server.js.map'
    - '../backend/output/index.js'
    - '../backend/output/index.js.map'
    - '../frontend/views/**'
    - '../frontend/public/**'
projectDir: ./

frameworkVersion: '2'
variablesResolutionMode: 20210326
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  lambdaHashingVersion: 20201221

functions:
  app:
    handler: output/server.handler
    events:
      - http: ANY /1972/09/11
      - http: 'ANY {proxy+}'

plugins:
  - serverless-offline
