service: backend
package:
  patterns:
    - '!../**/**'
    - '!**/**'
    - '../backend/package.json'
    - '../backend/node_modules/express'
    - '../backend/node_modules/serverless-http'
    - '../backend/output/server.js'
    - '../frontend/package.json'
    - '../frontend/views/**'
    - '../frontend/public/**'
projectDir: ./

frameworkVersion: '2'
variablesResolutionMode: 20210326
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  lambdaHashingVersion: 20201221

functions:
  app:
    handler: output/server.handler
    events:
      - http: ANY /1972/09/11
      - http: 'ANY {proxy+}'

plugins:
  - serverless-offline
