service: voximplant
package:
  patterns:
    - '!./output/**'
    - '!./tsconfig.json'
    - '!./apprunner.yaml'
    - 'output/index.js'
    - 'output/index.js.map'
projectDir: ./

frameworkVersion: '2'
variablesResolutionMode: 20210326
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  lambdaHashingVersion: 20201221

functions:
  app:
    handler: output/index.handler
    events:
      - http:
          path: /{any+}
          method: ANY

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4050
