service: backend
package:
  patterns:
    - '!./output/**'
    - '!./src/**'
    - '!./tsconfig.json'
    - 'output/server.js'
    - 'output/server.js.map'
    - 'output/index.js'
    - 'output/index.js.map'
    - '../frontend/views/**'
    - '../frontend/public/**'
projectDir: ./

frameworkVersion: '2'
variablesResolutionMode: 20210326
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  lambdaHashingVersion: 20201221

functions:
  app:
    handler: output/server.handler
    events:
      - http:
          path: /{any+}
          method: ANY

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4050
